### ISSUE TITLE
[제안] 리포트 생성 일자 추가

### ISSUE THREAD

**Issue by damilog** [hochan222/web-performance-monitoring#1]
안녕하세요, 모니터링 리포트 잘 보고 있습니다. 정말 잘 만드셨네요👍👍👍
혹시 리포트 상단에 리포트 생성 일자 추가해주실 수 있을지 문의 드립니다.

**Comment by hochan222** [comment]
안녕하세요! commit 날짜가 리포트 생성일입니다. 

commit history를 참고하여 이전 날짜에 대한 리포트를 확인하실 수 있습니다! 따라서, 리포트 생성 일자가 무의미하기에 별도로 추가하지는 않겠습니다!

답변이 늦어져서 넘넘 죄송해용 ㅜㅜ
